# The URL the site will be built for
base_url = "https://alexloz.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

theme = "gutenberg-portfolio"

[extra]
# Put all your custom variables here
portfolio_tracking_id = "UA-62288351-4"
#portfolio_name = "Alexander Lozada"
portfolio_video = "logotype.mp4"
portfolio_description = "Hey, what's up.  I'm Alexander Lozada and I'm a designer from Scranton, PA. I'm mainly interested in UI/UX, Motion, and 3D."
portfolio_contact = "alexanderpaullozada@gmail.com"