# The URL the site will be built for
base_url = "https://alexloz.com"
compile_sass = true
theme = "gutenberg-portfolio"

[extra]
portfolio_ackee_id = "bd91c871-a323-4e45-82cf-c35b3f027b0a"
portfolio_ackee_server = "https://ackee.u9h.design"
portfolio_video = "logotype.mp4"
portfolio_description = "Hey, what's up.  I'm Alexander Lozada and I'm a designer from Scranton, PA. I'm mainly interested in UI/UX, Motion, and 3D."
portfolio_contact = "alexanderpaullozada@gmail.com"
resume_url = "/media/resume/2019/alexander_lozada_resume.pdf"